@startuml UML

class Funcion {
  + ejecutar()
}

class Saludar {
  + ejecutar()
}

class Decorador {
  + envolver(func)
}

class Envoltura {
  + ejecutar()
}

Saludar --|> Funcion
Envoltura --|> Funcion

Decorador --> Funcion : recibe
Decorador --> Envoltura : retorna
Envoltura --> Funcion : delega

@enduml
